### ISSUE TITLE
Is this project the state-based adaptation of PeriPy？

### ISSUE THREAD

**Issue by Gabanzixiaohan** [jd-bartlett96/peridynamics#2]
I cant found it as a fork from the original PeriPy project,could you give me a more detailed guide to finding state-based adaptations？

**Comment by jd-bartlett96** [comment]
No, that is a separate fork of the PeriPy repo, and can be found here: https://github.com/jd-bartlett96/PeriPy

**Comment by Gabanzixiaohan** [comment]
Thank you very much for your answer! The peripy project currently only has bond-based examples, and I can't find how to do state- based simulation in the official documentation. Could you tell me where I can learn to use state-based theory for simulation in peripy?
